### ISSUE TITLE
Repository is empty

### ISSUE THREAD

**Issue by geyang** [benzhe/react-text-overflow-middle-ellipsis#1]
This poses a security risk. Please post code here, or take down the package.

**Comment by benzhe** [comment]
> This poses a security risk. Please post code here, or take down the package.

Hi, you can read the source code from NPM package.  e.g. https://cdn.jsdelivr.net/npm/react-text-overflow-middle-ellipsis@1.3.9/dist/index.js

Due to some restriction, I can't push any code to Github.
