### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by geyang** [benzhe/react-text-overflow-middle-ellipsis#2]
Thanks for this library! The codepen demo is not working. See screenshot below:

https://codepen.io/anon/pen/qoPyZW

![Screenshot 2019-06-17 21 56 54](https://user-images.githubusercontent.com/630490/59654390-d34a9a80-914a-11e9-83b4-e546b5dd5ab7.png)

**Comment by benzhe** [comment]
Checkout the stable version `1.3.9`. https://codepen.io/benzhe/pen/WqxPPg
